# manifest kubernetes file
apiVersion: apps/v1

kind: Deployment

metadata:
  name: book-deployment

  labels:
    app: books

spec:
  replicas: {{ .Values.deployment.replicas }}

  selector:
    matchLabels:
      app: books

  template:
    metadata:
      annotations:
        # prometheus.io/port: "3500"
        # prometheus.io/path: "/metrics"
        # prometheus.io/scrape: "true"
      labels:
        app: books

    spec:
      containers:
        - name: books

          image: docker.io/laykidi/books:{{ .Values.image.tag }}

          ports:
            - containerPort: {{ .Values.port }}
          env:
            - name: BOOK_PORT
              value: "3600"