# manifest kubernetes file
apiVersion: apps/v1

kind: Deployment

metadata:
  name: book-deployment

  labels:
    app: books

spec:
  replicas: {{ .Values.deployment.replicas }}

  selector:
    matchLabels:
      app: books

  template:
    metadata:
      annotations:
        # prometheus.io/port: "3500"
        # prometheus.io/path: "/metrics"
        # prometheus.io/scrape: "true"
      labels:
        app: books

    spec:
      containers:
        - name: books

          image: docker.io/laykidi/books:{{ .Values.image.tag }}
          imagePullPolicy: Always

          ports:
            - containerPort: {{ .Values.port }}
          env:
            - name: BOOK_PORT
              value: "3600"
            - name: HOST_IP
                  valueFrom:
                    fieldRef:
                      fieldPath: status.hostIP
           # the second env variable uses the previous variable.
            - name: OTEL_EXPORTER_OTLP_ENDPOINT  
              value: "http://$(HOST_IP):4317"
            - name: OTEL_SERVICE_NAME
              value: "fact-service"