apiVersion: apps/v1

kind: Deployment

metadata:
  name: customers-deployment

  labels:
    app: customers

spec:
  replicas: {{ .Values.deployment.replicas }}

  selector:
    matchLabels:
      app: customers

  template:
    metadata:
      annotations:
        # prometheus.io/port: "3500"
        # prometheus.io/path: "/metrics"
        # prometheus.io/scrape: "true"
      labels:
        app: customers

    spec:
      containers:
        - name: customers

          image: docker.io/laykidi/customers:{{ .Values.image.tag }}
          imagePullPolicy: Always

          ports:
            - containerPort: {{ .Values.port }}
          env:
            - name: CUSTOMER_PORT
              value: "3700"
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
           # the second env variable uses the previous variable.
            - name: OTEL_EXPORTER_OTLP_ENDPOINT  
              value: "http://$(HOST_IP):4317"
            - name: OTEL_SERVICE_NAME
              value: "fact-service"