apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: book-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Hazem-Atya/book-shop'

    path: 02-charts/books-service
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated: {}
    # syncOptions:
    #   - CreateNamespace=true

