# manifest kubernetes file
apiVersion: apps/v1

kind: Deployment

metadata:
  name: api-gateway-deployment

  labels:
    app: api-gateway

spec:
  replicas: {{ .Values.deployment.replicas }}

  selector:
    matchLabels:
      app: api-gateway

  template:
    metadata:
      annotations:
      prometheus.io/port: "3900"
      prometheus.io/path: "/metrics"
      prometheus.io/scrape: "true"
      labels:
        app: api-gateway

    spec:
      containers:
        - name: api-gateway

          image: docker.io/laykidi/api-gateway:{{.Values.image.tag}}
          imagePullPolicy: Always

          ports:
            - containerPort: {{ .Values.port }}
          env:
            - name: API_GATEWAY_PORT
              value: "3900"
            - name: BOOK_HOST
              value: "book-service.default.svc.cluster.local"
            - name: BOOK_PORT
              value: "80"
            - name: CUSTOMER_HOST
              value: "customer-service.default.svc.cluster.local"
            - name: CUSTOMER_PORT
              value: "80"
            - name: ORDER_HOST
              value: "order-service.default.svc.cluster.local"
            - name: ORDER_PORT
              value: "80"
