apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  selector:
    app: api-gateway
  ports:
  - nodePort: 30007
    port: 80
    protocol: TCP
    targetPort: 3900
  type: NodePort