apiVersion: apps/v1

kind: Deployment

metadata:
  name: orders-deployment

  labels:
    app: orders

spec:
  replicas: {{ .Values.deployment.replicas }}

  selector:
    matchLabels:
      app: orders

  template:
    metadata:
      annotations:
        # prometheus.io/port: "3500"
        # prometheus.io/path: "/metrics"
        # prometheus.io/scrape: "true"
      labels:
        app: orders

    spec:
      containers:
        - name: orders

          image: docker.io/laykidi/orders:{{ .Values.image.tag }}
          imagePullPolicy: Always

          ports:
            - containerPort: {{ .Values.port }}
          env:
            - name: ORDER_PORT
              value: "3800"
            - name: BOOK_HOST
              value: "book-service.default.svc.cluster.local"
            - name: BOOK_PORT
              value: "80"
            - name: CUSTOMER_HOST
              value: "customer-service.default.svc.cluster.local"
            - name: CUSTOMER_PORT
              value: "80"
