name: DevOps pipeline project
on: [push]
jobs:
  # Test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out repository code
  #       uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: '15'
  #     - name: 'Creating the .env file'  # this file contains the connection string to the mongo DB
  #       run: |
  #         touch  .env
  #         echo DB_CONNECTION_STRING="${{ secrets.MONGODB_CONNECTION_STRING }}" >> .env
  #     - run: npm install
  Build-books-svc:
    runs-on: ubuntu-latest
    # needs:
    #      - Test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to   Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx # The builder, this is where docker is going to be installed
        uses: docker/setup-buildx-action@v1
      - name: "Creating the .env file" # this file contains the connection string to the mongo DB
        run: |
          touch .env
          echo MONGO_URL="${{ secrets.MONGODB_CONNECTION_STRING }}" >> books/.env
      - name: Build and push
        uses: docker/build-push-action@v2

        with:
          context: books/
          file: books/Dockerfile
          push: true # will it push or just build
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/books # tag of the image
          # tags: ${{ secrets.DOCKER_HUB_USERNAME }}/books:${{github.sha}} # tag of the image
  Build-customers-svc:
    runs-on: ubuntu-latest
    # needs:
    #      - Test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to   Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx # The builder, this is where docker is going to be installed
        uses: docker/setup-buildx-action@v1
      - name: "Creating the .env file" # this file contains the connection string to the mongo DB
        run: |
          touch .env
          echo MONGO_URL="${{ secrets.MONGODB_CONNECTION_STRING }}" >> customers/.env
      - name: Build and push
        uses: docker/build-push-action@v2

        with:
          context: customers/
          file: customers/Dockerfile
          push: true # will it push or just build
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/customers # tag of the image
          # tags: ${{ secrets.DOCKER_HUB_USERNAME }}/customers:${{github.sha}} # tag of the image

  Build-orders-svc:
    runs-on: ubuntu-latest
    # needs:
    #      - Test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to   Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx # The builder, this is where docker is going to be installed
        uses: docker/setup-buildx-action@v1
      - name: "Creating the .env file" # this file contains the connection string to the mongo DB
        run: |
          touch .env
          echo MONGO_URL="${{ secrets.MONGODB_CONNECTION_STRING }}" >> orders/.env
      - name: Build and push
        uses: docker/build-push-action@v2

        with:
          context: orders/
          file: orders/Dockerfile
          push: true # will it push or just build
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/customers:${{github.sha}} # tag of the image
          # tags: ${{ secrets.DOCKER_HUB_USERNAME }}/customers:${{github.sha}} # tag of the image
